### ISSUE TITLE
Update to latest version of Bootstrap v3

### ISSUE THREAD

**Issue by coliff** [mkdocs/mkdocs-bootstrap#10]
It'd be good to update to the latest version of Bootstrap (v3.3.7). Shall I open a PR?

**Comment by d0ugal** [comment]
Yup, that would be great. I don't know how easy it would be.

**Comment by coliff** [comment]
I opened a PR for this; https://github.com/mkdocs/mkdocs-bootstrap/pull/11
Straight forward replacing the JS and CSS files

**Comment by coliff** [comment]
Thanks for merging the PR. I'll close this issue now.
