### ISSUE TITLE
Version 1.1 wheel package distribution is broken

### ISSUE THREAD

**Issue by lvjp** [mkdocs/mkdocs-bootstrap#32]
I think that the released 1.1 version have a broken wheel package.

# Bug
Only with those command
```bash
$ mkdocs new website
$ mkdocs build
```
When you open the website, you can observe a big white space between the top of the screen and the top menu.

# Primary cause
After some investigation, I found that the version 1.1 use bootstrap version 4 but if you install wheel package, it will generate an index.html like this :
```html
<link href="css/bootstrap-3.3.7.min.css" rel="stylesheet">
<script src="js/bootstrap-3.3.7.min.js" defer></script>
```
With those files :
```
css/bootstrap.min.css
css/bootstrap-3.3.7.min.css
js/bootstrap-3.3.7.min.js
js/bootstrap.min.js
```

# Root cause
If look for bootstrap files inside `mkdocs-bootstrap-1.1.tar.gz` and `mkdocs_bootstrap-1.1-py2.py3-none-any.whl`, you will be surprised

_                        | `.tar.gz` | `.whl`
-------------|----------|------
css/bootstrap.min.css         |  present | 
css/bootstrap-3.3.7.min.cs |  | present
js/bootstrap-3.3.7.min.js      | present | present
grep bootstrap main.html    | `bootstrap-3.3.7.min.js` | `bootstrap.min.js`

# A workaround
When installing theme the flag `--no-binary :all:` can be used. This permit to use the not bugged `.tar.gz` file.

# A way to fix the problem
You can maybe create a new version `1.1.1` with a fixed wheel package.
I think that override the `1.1` version is a bad thing because local mirroring software will may not download a new file with the same version number.

**Comment by waylan** [comment]
I just checked the wheel and there is no problem with the wheel itself. My guess is that you installed the new version over the old one, which failed to remove the old files for some reason. I would suggest uninstalling, then reinstalling. See if that works for you.

```
pip uninstall mkdocs
pip install mkdocs
```

**Comment by lvjp** [comment]
When I said :
> If you look for bootstrap files inside mkdocs-bootstrap-1.1.tar.gz and mkdocs_bootstrap-1.1-py2.py3-none-any.whl, you will be surprised.
I talked about file freshly downloaded from https://pypi.org

Here my file check process :
```bash
$ # Check mkdocs_bootstrap-1.1-py2.py3-none-any.whl
$ wget -q https://files.pythonhosted.org/packages/54/52/d9b9e58e5c8962f64bbdbc6b23ae192b92d8c0e25793e4e5696b55948ebc/mkdocs_bootstrap-1.1-py2.py3-none-any.whl
$ unzip -qql mkdocs_bootstrap-1.1-py2.py3-none-any.whl '**/bootstrap*'
   121200  2018-08-03 12:37   mkdocs_bootstrap/css/bootstrap-3.3.7.min.css
   159515  2020-02-05 19:21   mkdocs_bootstrap/css/bootstrap.min.css
    37045  2018-08-03 12:37   mkdocs_bootstrap/js/bootstrap-3.3.7.min.js
$ # Check mkdocs-bootstrap-1.1.tar.gz
$ wget -qO - https://files.pythonhosted.org/packages/c2/bc/5e5709f5bbc70eeb4453dbfc6120bafe8fd69d115a97548c24f1b939ed13/mkdocs-bootstrap-1.1.tar.gz | tar -tzvf - | grep "/bootstrap[^/]\+"
-rw-r--r-- waylan/staff 159515 2020-02-06 01:21 mkdocs-bootstrap-1.1/mkdocs_bootstrap/css/bootstrap.min.css
```

As you can see, the problem is inside the publicly available archive from https://pypi.org

**Comment by waylan** [comment]
Opps, sorry, you are correct. I wasn't paying attention and missed this was the **bootstrap** project. I checked the wrong project. Yes, I see the old files still exist. This is a bug. Thank you for the report.

**Comment by rodneytamblyn** [comment]
Still seems to be present....

**Comment by waylan** [comment]
Sorry for the very delayed response. Guess I forgot about it. In any event, I have just deployed version 1.1.1 which should have fixed the issue.
